---
- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    daemon_reload: yes
    enabled: yes
